./dalgen.sh apps
./dalgen.sh auth_keys
./dalgen.sh auth_phone_transactions
./dalgen.sh auth_seq_updates
./dalgen.sh auth_updates_state
./dalgen.sh auth_users
./dalgen.sh auths
./dalgen.sh banned
./dalgen.sh chat_participants
./dalgen.sh chats
./dalgen.sh devices
./dalgen.sh messages
./dalgen.sh phone_call_sessions
./dalgen.sh reports
./dalgen.sh sticker_packs
./dalgen.sh sticker_sets
./dalgen.sh tmp_passwords
./dalgen.sh user_contacts
./dalgen.sh user_dialogs
./dalgen.sh user_notify_settings
./dalgen.sh user_passwords
./dalgen.sh user_presences
./dalgen.sh user_privacys
./dalgen.sh user_pts_updates
./dalgen.sh user_qts_updates
./dalgen.sh users
./dalgen.sh wall_papers

