// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status.proto

package status

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// //////////////////////////////////////////////////////////////////////////////////////
type Int32 struct {
	V                    int32    `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32) Reset()         { *m = Int32{} }
func (m *Int32) String() string { return proto.CompactTextString(m) }
func (*Int32) ProtoMessage()    {}
func (*Int32) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_646caa935c956df1, []int{0}
}
func (m *Int32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32.Unmarshal(m, b)
}
func (m *Int32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32.Marshal(b, m, deterministic)
}
func (dst *Int32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32.Merge(dst, src)
}
func (m *Int32) XXX_Size() int {
	return xxx_messageInfo_Int32.Size(m)
}
func (m *Int32) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32.DiscardUnknown(m)
}

var xxx_messageInfo_Int32 proto.InternalMessageInfo

func (m *Int32) GetV() int32 {
	if m != nil {
		return m.V
	}
	return 0
}

type Int32List struct {
	Vlist                []int32  `protobuf:"varint,1,rep,packed,name=vlist,proto3" json:"vlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32List) Reset()         { *m = Int32List{} }
func (m *Int32List) String() string { return proto.CompactTextString(m) }
func (*Int32List) ProtoMessage()    {}
func (*Int32List) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_646caa935c956df1, []int{1}
}
func (m *Int32List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32List.Unmarshal(m, b)
}
func (m *Int32List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32List.Marshal(b, m, deterministic)
}
func (dst *Int32List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32List.Merge(dst, src)
}
func (m *Int32List) XXX_Size() int {
	return xxx_messageInfo_Int32List.Size(m)
}
func (m *Int32List) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32List.DiscardUnknown(m)
}

var xxx_messageInfo_Int32List proto.InternalMessageInfo

func (m *Int32List) GetVlist() []int32 {
	if m != nil {
		return m.Vlist
	}
	return nil
}

type Int64List struct {
	Vlist                []int64  `protobuf:"varint,1,rep,packed,name=vlist,proto3" json:"vlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64List) Reset()         { *m = Int64List{} }
func (m *Int64List) String() string { return proto.CompactTextString(m) }
func (*Int64List) ProtoMessage()    {}
func (*Int64List) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_646caa935c956df1, []int{2}
}
func (m *Int64List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64List.Unmarshal(m, b)
}
func (m *Int64List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64List.Marshal(b, m, deterministic)
}
func (dst *Int64List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64List.Merge(dst, src)
}
func (m *Int64List) XXX_Size() int {
	return xxx_messageInfo_Int64List.Size(m)
}
func (m *Int64List) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64List.DiscardUnknown(m)
}

var xxx_messageInfo_Int64List proto.InternalMessageInfo

func (m *Int64List) GetVlist() []int64 {
	if m != nil {
		return m.Vlist
	}
	return nil
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_646caa935c956df1, []int{3}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

// //////////////////////////////////////////////////////////////////////////////////////
type SessionEntry struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServerId             int32    `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	AuthKeyId            int64    `protobuf:"varint,3,opt,name=auth_key_id,json=authKeyId,proto3" json:"auth_key_id,omitempty"`
	Expired              int64    `protobuf:"varint,4,opt,name=expired,proto3" json:"expired,omitempty"`
	Layer                int32    `protobuf:"varint,5,opt,name=layer,proto3" json:"layer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionEntry) Reset()         { *m = SessionEntry{} }
func (m *SessionEntry) String() string { return proto.CompactTextString(m) }
func (*SessionEntry) ProtoMessage()    {}
func (*SessionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_646caa935c956df1, []int{4}
}
func (m *SessionEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionEntry.Unmarshal(m, b)
}
func (m *SessionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionEntry.Marshal(b, m, deterministic)
}
func (dst *SessionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionEntry.Merge(dst, src)
}
func (m *SessionEntry) XXX_Size() int {
	return xxx_messageInfo_SessionEntry.Size(m)
}
func (m *SessionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SessionEntry proto.InternalMessageInfo

func (m *SessionEntry) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SessionEntry) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *SessionEntry) GetAuthKeyId() int64 {
	if m != nil {
		return m.AuthKeyId
	}
	return 0
}

func (m *SessionEntry) GetExpired() int64 {
	if m != nil {
		return m.Expired
	}
	return 0
}

func (m *SessionEntry) GetLayer() int32 {
	if m != nil {
		return m.Layer
	}
	return 0
}

type SessionEntryList struct {
	Sessions             []*SessionEntry `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SessionEntryList) Reset()         { *m = SessionEntryList{} }
func (m *SessionEntryList) String() string { return proto.CompactTextString(m) }
func (*SessionEntryList) ProtoMessage()    {}
func (*SessionEntryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_646caa935c956df1, []int{5}
}
func (m *SessionEntryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionEntryList.Unmarshal(m, b)
}
func (m *SessionEntryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionEntryList.Marshal(b, m, deterministic)
}
func (dst *SessionEntryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionEntryList.Merge(dst, src)
}
func (m *SessionEntryList) XXX_Size() int {
	return xxx_messageInfo_SessionEntryList.Size(m)
}
func (m *SessionEntryList) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionEntryList.DiscardUnknown(m)
}

var xxx_messageInfo_SessionEntryList proto.InternalMessageInfo

func (m *SessionEntryList) GetSessions() []*SessionEntry {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type UsersSessionEntryList struct {
	UsersSessions        map[int32]*SessionEntryList `protobuf:"bytes,1,rep,name=users_sessions,json=usersSessions,proto3" json:"users_sessions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *UsersSessionEntryList) Reset()         { *m = UsersSessionEntryList{} }
func (m *UsersSessionEntryList) String() string { return proto.CompactTextString(m) }
func (*UsersSessionEntryList) ProtoMessage()    {}
func (*UsersSessionEntryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_status_646caa935c956df1, []int{6}
}
func (m *UsersSessionEntryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersSessionEntryList.Unmarshal(m, b)
}
func (m *UsersSessionEntryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersSessionEntryList.Marshal(b, m, deterministic)
}
func (dst *UsersSessionEntryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersSessionEntryList.Merge(dst, src)
}
func (m *UsersSessionEntryList) XXX_Size() int {
	return xxx_messageInfo_UsersSessionEntryList.Size(m)
}
func (m *UsersSessionEntryList) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersSessionEntryList.DiscardUnknown(m)
}

var xxx_messageInfo_UsersSessionEntryList proto.InternalMessageInfo

func (m *UsersSessionEntryList) GetUsersSessions() map[int32]*SessionEntryList {
	if m != nil {
		return m.UsersSessions
	}
	return nil
}

func init() {
	proto.RegisterType((*Int32)(nil), "status.Int32")
	proto.RegisterType((*Int32List)(nil), "status.Int32List")
	proto.RegisterType((*Int64List)(nil), "status.Int64List")
	proto.RegisterType((*Void)(nil), "status.Void")
	proto.RegisterType((*SessionEntry)(nil), "status.SessionEntry")
	proto.RegisterType((*SessionEntryList)(nil), "status.SessionEntryList")
	proto.RegisterType((*UsersSessionEntryList)(nil), "status.UsersSessionEntryList")
	proto.RegisterMapType((map[int32]*SessionEntryList)(nil), "status.UsersSessionEntryList.UsersSessionsEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCStatusClient is the client API for RPCStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCStatusClient interface {
	SetSessionOnline(ctx context.Context, in *SessionEntry, opts ...grpc.CallOption) (*Void, error)
	SetSessionOffline(ctx context.Context, in *SessionEntry, opts ...grpc.CallOption) (*Void, error)
	GetUserOnlineSessions(ctx context.Context, in *Int32, opts ...grpc.CallOption) (*SessionEntryList, error)
	GetUsersOnlineSessionsList(ctx context.Context, in *Int32List, opts ...grpc.CallOption) (*UsersSessionEntryList, error)
}

type rPCStatusClient struct {
	cc *grpc.ClientConn
}

func NewRPCStatusClient(cc *grpc.ClientConn) RPCStatusClient {
	return &rPCStatusClient{cc}
}

func (c *rPCStatusClient) SetSessionOnline(ctx context.Context, in *SessionEntry, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/status.RPCStatus/SetSessionOnline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCStatusClient) SetSessionOffline(ctx context.Context, in *SessionEntry, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/status.RPCStatus/SetSessionOffline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCStatusClient) GetUserOnlineSessions(ctx context.Context, in *Int32, opts ...grpc.CallOption) (*SessionEntryList, error) {
	out := new(SessionEntryList)
	err := c.cc.Invoke(ctx, "/status.RPCStatus/GetUserOnlineSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCStatusClient) GetUsersOnlineSessionsList(ctx context.Context, in *Int32List, opts ...grpc.CallOption) (*UsersSessionEntryList, error) {
	out := new(UsersSessionEntryList)
	err := c.cc.Invoke(ctx, "/status.RPCStatus/GetUsersOnlineSessionsList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCStatusServer is the server API for RPCStatus service.
type RPCStatusServer interface {
	SetSessionOnline(context.Context, *SessionEntry) (*Void, error)
	SetSessionOffline(context.Context, *SessionEntry) (*Void, error)
	GetUserOnlineSessions(context.Context, *Int32) (*SessionEntryList, error)
	GetUsersOnlineSessionsList(context.Context, *Int32List) (*UsersSessionEntryList, error)
}

func RegisterRPCStatusServer(s *grpc.Server, srv RPCStatusServer) {
	s.RegisterService(&_RPCStatus_serviceDesc, srv)
}

func _RPCStatus_SetSessionOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCStatusServer).SetSessionOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/status.RPCStatus/SetSessionOnline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCStatusServer).SetSessionOnline(ctx, req.(*SessionEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCStatus_SetSessionOffline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCStatusServer).SetSessionOffline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/status.RPCStatus/SetSessionOffline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCStatusServer).SetSessionOffline(ctx, req.(*SessionEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCStatus_GetUserOnlineSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int32)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCStatusServer).GetUserOnlineSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/status.RPCStatus/GetUserOnlineSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCStatusServer).GetUserOnlineSessions(ctx, req.(*Int32))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCStatus_GetUsersOnlineSessionsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Int32List)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCStatusServer).GetUsersOnlineSessionsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/status.RPCStatus/GetUsersOnlineSessionsList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCStatusServer).GetUsersOnlineSessionsList(ctx, req.(*Int32List))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCStatus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "status.RPCStatus",
	HandlerType: (*RPCStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetSessionOnline",
			Handler:    _RPCStatus_SetSessionOnline_Handler,
		},
		{
			MethodName: "SetSessionOffline",
			Handler:    _RPCStatus_SetSessionOffline_Handler,
		},
		{
			MethodName: "GetUserOnlineSessions",
			Handler:    _RPCStatus_GetUserOnlineSessions_Handler,
		},
		{
			MethodName: "GetUsersOnlineSessionsList",
			Handler:    _RPCStatus_GetUsersOnlineSessionsList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "status.proto",
}

func init() { proto.RegisterFile("status.proto", fileDescriptor_status_646caa935c956df1) }

var fileDescriptor_status_646caa935c956df1 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x51, 0xcb, 0xd3, 0x30,
	0x14, 0x25, 0xed, 0xd7, 0x7e, 0x5f, 0x6f, 0x3b, 0xd9, 0xc2, 0x86, 0xa5, 0xa2, 0xcc, 0x3e, 0x0d,
	0x84, 0x32, 0x3a, 0x99, 0xe2, 0x93, 0x4c, 0x45, 0x8b, 0xa2, 0xa3, 0x43, 0x05, 0x5f, 0x46, 0x67,
	0x33, 0x0c, 0xab, 0xed, 0x68, 0xd2, 0x62, 0xff, 0x84, 0x4f, 0xfe, 0x2c, 0x7f, 0x94, 0x24, 0x69,
	0xa5, 0x73, 0x53, 0x7c, 0xeb, 0x3d, 0xf7, 0xdc, 0x73, 0x7b, 0x4e, 0x12, 0x70, 0x18, 0x4f, 0x78,
	0xc5, 0x82, 0x63, 0x59, 0xf0, 0x02, 0x9b, 0xaa, 0xf2, 0x27, 0x60, 0x44, 0x39, 0x5f, 0x84, 0xd8,
	0x01, 0x54, 0xbb, 0x68, 0x8a, 0x66, 0x46, 0x8c, 0x6a, 0xff, 0x3e, 0x58, 0x12, 0x7e, 0x43, 0x19,
	0xc7, 0x63, 0x30, 0xea, 0x8c, 0x32, 0xee, 0xa2, 0xa9, 0x3e, 0x33, 0x62, 0x55, 0xb4, 0x94, 0xe5,
	0xc3, 0x73, 0x8a, 0xde, 0x51, 0x4c, 0xb8, 0xfa, 0x50, 0xd0, 0xd4, 0xff, 0x81, 0xc0, 0xd9, 0x10,
	0xc6, 0x68, 0x91, 0xbf, 0xc8, 0x79, 0xd9, 0xe0, 0xdb, 0x70, 0x5d, 0x31, 0x52, 0x6e, 0x69, 0xda,
	0xae, 0x34, 0x45, 0x19, 0xa5, 0xf8, 0x0e, 0x58, 0x8c, 0x94, 0xb5, 0x6a, 0x69, 0xb2, 0x75, 0xa3,
	0x80, 0x28, 0xc5, 0xf7, 0xc0, 0x4e, 0x2a, 0xfe, 0x65, 0x7b, 0x20, 0x8d, 0x68, 0xeb, 0x53, 0x34,
	0xd3, 0x63, 0x4b, 0x40, 0xaf, 0x49, 0x13, 0xa5, 0xd8, 0x85, 0x6b, 0xf2, 0xed, 0x48, 0x4b, 0x92,
	0xba, 0x57, 0xb2, 0xd7, 0x95, 0xe2, 0xf7, 0xb2, 0xa4, 0x21, 0xa5, 0x6b, 0x48, 0x49, 0x55, 0xf8,
	0xcf, 0x61, 0xd8, 0xff, 0x2b, 0x69, 0x64, 0x0e, 0x37, 0x4c, 0x61, 0x4c, 0x7a, 0xb1, 0xc3, 0x71,
	0xd0, 0x06, 0xd7, 0xe7, 0xc6, 0xbf, 0x59, 0xfe, 0x4f, 0x04, 0x93, 0xf7, 0x8c, 0x94, 0xec, 0x4c,
	0xeb, 0x23, 0xdc, 0x12, 0xb6, 0xd8, 0xf6, 0x0f, 0xc5, 0x79, 0xa7, 0x78, 0x71, 0xec, 0x04, 0x65,
	0x6a, 0xdb, 0xa0, 0xea, 0x63, 0xde, 0x27, 0xc0, 0xe7, 0x24, 0x3c, 0x04, 0xfd, 0x40, 0x9a, 0x36,
	0x50, 0xf1, 0x89, 0x03, 0x30, 0xea, 0x24, 0xab, 0x88, 0x4c, 0xd2, 0x0e, 0xdd, 0x4b, 0x4e, 0xc4,
	0xca, 0x58, 0xd1, 0x9e, 0x68, 0x8f, 0x51, 0xf8, 0x5d, 0x03, 0x2b, 0x5e, 0x3f, 0xdb, 0x48, 0x26,
	0x5e, 0x8a, 0x88, 0x78, 0xcb, 0x7f, 0x97, 0x67, 0x34, 0x27, 0xf8, 0x62, 0x20, 0x9e, 0xd3, 0xa1,
	0xe2, 0xc4, 0xf1, 0x23, 0x18, 0xf5, 0xe6, 0xf6, 0xfb, 0xff, 0x1e, 0x7c, 0x0a, 0x93, 0x97, 0x84,
	0x0b, 0x77, 0x6a, 0x5b, 0x67, 0x11, 0x0f, 0x3a, 0x9a, 0xbc, 0x97, 0xde, 0x5f, 0xbd, 0xe0, 0xb7,
	0xe0, 0xb5, 0x0a, 0xec, 0x54, 0x42, 0x76, 0x47, 0x27, 0x32, 0x02, 0xf2, 0xee, 0xfe, 0xf3, 0x38,
	0x56, 0x0f, 0xc0, 0xa5, 0x5f, 0x83, 0x9c, 0xec, 0xaa, 0x2c, 0x09, 0xc4, 0x5d, 0xa4, 0x9f, 0x49,
	0x3b, 0xb1, 0xb2, 0x55, 0x4c, 0x6b, 0xf1, 0xa4, 0x5e, 0x69, 0x6b, 0xb4, 0x33, 0xe5, 0xeb, 0x5a,
	0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xee, 0x78, 0xd8, 0x6d, 0x03, 0x00, 0x00,
}
