// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.tl.core_types.proto

package mtproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// /////////////////////////////////////////////////////////////////////////////
// Bool <--
//  + TL_boolFalse
//  + TL_boolTrue
//
type Bool_Data struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool_Data) Reset()         { *m = Bool_Data{} }
func (m *Bool_Data) String() string { return proto.CompactTextString(m) }
func (*Bool_Data) ProtoMessage()    {}
func (*Bool_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{0}
}
func (m *Bool_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool_Data.Unmarshal(m, b)
}
func (m *Bool_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool_Data.Marshal(b, m, deterministic)
}
func (dst *Bool_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool_Data.Merge(dst, src)
}
func (m *Bool_Data) XXX_Size() int {
	return xxx_messageInfo_Bool_Data.Size(m)
}
func (m *Bool_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Bool_Data proto.InternalMessageInfo

type Bool struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *Bool_Data    `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{1}
}
func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (dst *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(dst, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *Bool) GetData2() *Bool_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// boolFalse#bc799737 = Bool;
type TLBoolFalse struct {
	Data2                *Bool_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TLBoolFalse) Reset()         { *m = TLBoolFalse{} }
func (m *TLBoolFalse) String() string { return proto.CompactTextString(m) }
func (*TLBoolFalse) ProtoMessage()    {}
func (*TLBoolFalse) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{2}
}
func (m *TLBoolFalse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLBoolFalse.Unmarshal(m, b)
}
func (m *TLBoolFalse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLBoolFalse.Marshal(b, m, deterministic)
}
func (dst *TLBoolFalse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLBoolFalse.Merge(dst, src)
}
func (m *TLBoolFalse) XXX_Size() int {
	return xxx_messageInfo_TLBoolFalse.Size(m)
}
func (m *TLBoolFalse) XXX_DiscardUnknown() {
	xxx_messageInfo_TLBoolFalse.DiscardUnknown(m)
}

var xxx_messageInfo_TLBoolFalse proto.InternalMessageInfo

func (m *TLBoolFalse) GetData2() *Bool_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// boolTrue#997275b5 = Bool;
type TLBoolTrue struct {
	Data2                *Bool_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TLBoolTrue) Reset()         { *m = TLBoolTrue{} }
func (m *TLBoolTrue) String() string { return proto.CompactTextString(m) }
func (*TLBoolTrue) ProtoMessage()    {}
func (*TLBoolTrue) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{3}
}
func (m *TLBoolTrue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLBoolTrue.Unmarshal(m, b)
}
func (m *TLBoolTrue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLBoolTrue.Marshal(b, m, deterministic)
}
func (dst *TLBoolTrue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLBoolTrue.Merge(dst, src)
}
func (m *TLBoolTrue) XXX_Size() int {
	return xxx_messageInfo_TLBoolTrue.Size(m)
}
func (m *TLBoolTrue) XXX_DiscardUnknown() {
	xxx_messageInfo_TLBoolTrue.DiscardUnknown(m)
}

var xxx_messageInfo_TLBoolTrue proto.InternalMessageInfo

func (m *TLBoolTrue) GetData2() *Bool_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// True <--
//  + TL_true
//
type True_Data struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *True_Data) Reset()         { *m = True_Data{} }
func (m *True_Data) String() string { return proto.CompactTextString(m) }
func (*True_Data) ProtoMessage()    {}
func (*True_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{4}
}
func (m *True_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_True_Data.Unmarshal(m, b)
}
func (m *True_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_True_Data.Marshal(b, m, deterministic)
}
func (dst *True_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_True_Data.Merge(dst, src)
}
func (m *True_Data) XXX_Size() int {
	return xxx_messageInfo_True_Data.Size(m)
}
func (m *True_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_True_Data.DiscardUnknown(m)
}

var xxx_messageInfo_True_Data proto.InternalMessageInfo

type True struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *True_Data    `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *True) Reset()         { *m = True{} }
func (m *True) String() string { return proto.CompactTextString(m) }
func (*True) ProtoMessage()    {}
func (*True) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{5}
}
func (m *True) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_True.Unmarshal(m, b)
}
func (m *True) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_True.Marshal(b, m, deterministic)
}
func (dst *True) XXX_Merge(src proto.Message) {
	xxx_messageInfo_True.Merge(dst, src)
}
func (m *True) XXX_Size() int {
	return xxx_messageInfo_True.Size(m)
}
func (m *True) XXX_DiscardUnknown() {
	xxx_messageInfo_True.DiscardUnknown(m)
}

var xxx_messageInfo_True proto.InternalMessageInfo

func (m *True) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *True) GetData2() *True_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// true#3fedd339 = True;
type TLTrue struct {
	Data2                *True_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TLTrue) Reset()         { *m = TLTrue{} }
func (m *TLTrue) String() string { return proto.CompactTextString(m) }
func (*TLTrue) ProtoMessage()    {}
func (*TLTrue) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{6}
}
func (m *TLTrue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLTrue.Unmarshal(m, b)
}
func (m *TLTrue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLTrue.Marshal(b, m, deterministic)
}
func (dst *TLTrue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLTrue.Merge(dst, src)
}
func (m *TLTrue) XXX_Size() int {
	return xxx_messageInfo_TLTrue.Size(m)
}
func (m *TLTrue) XXX_DiscardUnknown() {
	xxx_messageInfo_TLTrue.DiscardUnknown(m)
}

var xxx_messageInfo_TLTrue proto.InternalMessageInfo

func (m *TLTrue) GetData2() *True_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// Error <--
//  + TL_error
//
type Error_Data struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error_Data) Reset()         { *m = Error_Data{} }
func (m *Error_Data) String() string { return proto.CompactTextString(m) }
func (*Error_Data) ProtoMessage()    {}
func (*Error_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{7}
}
func (m *Error_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error_Data.Unmarshal(m, b)
}
func (m *Error_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error_Data.Marshal(b, m, deterministic)
}
func (dst *Error_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error_Data.Merge(dst, src)
}
func (m *Error_Data) XXX_Size() int {
	return xxx_messageInfo_Error_Data.Size(m)
}
func (m *Error_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Error_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Error_Data proto.InternalMessageInfo

func (m *Error_Data) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error_Data) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Error struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *Error_Data   `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{8}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *Error) GetData2() *Error_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// error#c4b9f9bb code:int text:string = Error;
type TLError struct {
	Data2                *Error_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TLError) Reset()         { *m = TLError{} }
func (m *TLError) String() string { return proto.CompactTextString(m) }
func (*TLError) ProtoMessage()    {}
func (*TLError) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{9}
}
func (m *TLError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLError.Unmarshal(m, b)
}
func (m *TLError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLError.Marshal(b, m, deterministic)
}
func (dst *TLError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLError.Merge(dst, src)
}
func (m *TLError) XXX_Size() int {
	return xxx_messageInfo_TLError.Size(m)
}
func (m *TLError) XXX_DiscardUnknown() {
	xxx_messageInfo_TLError.DiscardUnknown(m)
}

var xxx_messageInfo_TLError proto.InternalMessageInfo

func (m *TLError) GetData2() *Error_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// /////////////////////////////////////////////////////////////////////////////
// Null <--
//  + TL_null
//
type Null_Data struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null_Data) Reset()         { *m = Null_Data{} }
func (m *Null_Data) String() string { return proto.CompactTextString(m) }
func (*Null_Data) ProtoMessage()    {}
func (*Null_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{10}
}
func (m *Null_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null_Data.Unmarshal(m, b)
}
func (m *Null_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null_Data.Marshal(b, m, deterministic)
}
func (dst *Null_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null_Data.Merge(dst, src)
}
func (m *Null_Data) XXX_Size() int {
	return xxx_messageInfo_Null_Data.Size(m)
}
func (m *Null_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Null_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Null_Data proto.InternalMessageInfo

type Null struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Data2                *Null_Data    `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{11}
}
func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (dst *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(dst, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

func (m *Null) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (m *Null) GetData2() *Null_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

// null#56730bcc = Null;
type TLNull struct {
	Data2                *Null_Data `protobuf:"bytes,2,opt,name=data2,proto3" json:"data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TLNull) Reset()         { *m = TLNull{} }
func (m *TLNull) String() string { return proto.CompactTextString(m) }
func (*TLNull) ProtoMessage()    {}
func (*TLNull) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_core_types_3fbe56126998b15b, []int{12}
}
func (m *TLNull) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLNull.Unmarshal(m, b)
}
func (m *TLNull) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLNull.Marshal(b, m, deterministic)
}
func (dst *TLNull) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLNull.Merge(dst, src)
}
func (m *TLNull) XXX_Size() int {
	return xxx_messageInfo_TLNull.Size(m)
}
func (m *TLNull) XXX_DiscardUnknown() {
	xxx_messageInfo_TLNull.DiscardUnknown(m)
}

var xxx_messageInfo_TLNull proto.InternalMessageInfo

func (m *TLNull) GetData2() *Null_Data {
	if m != nil {
		return m.Data2
	}
	return nil
}

func init() {
	proto.RegisterType((*Bool_Data)(nil), "mtproto.Bool_Data")
	proto.RegisterType((*Bool)(nil), "mtproto.Bool")
	proto.RegisterType((*TLBoolFalse)(nil), "mtproto.TL_boolFalse")
	proto.RegisterType((*TLBoolTrue)(nil), "mtproto.TL_boolTrue")
	proto.RegisterType((*True_Data)(nil), "mtproto.True_Data")
	proto.RegisterType((*True)(nil), "mtproto.True")
	proto.RegisterType((*TLTrue)(nil), "mtproto.TL_true")
	proto.RegisterType((*Error_Data)(nil), "mtproto.Error_Data")
	proto.RegisterType((*Error)(nil), "mtproto.Error")
	proto.RegisterType((*TLError)(nil), "mtproto.TL_error")
	proto.RegisterType((*Null_Data)(nil), "mtproto.Null_Data")
	proto.RegisterType((*Null)(nil), "mtproto.Null")
	proto.RegisterType((*TLNull)(nil), "mtproto.TL_null")
}

func init() {
	proto.RegisterFile("schema.tl.core_types.proto", fileDescriptor_schema_tl_core_types_3fbe56126998b15b)
}

var fileDescriptor_schema_tl_core_types_3fbe56126998b15b = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcf, 0x4b, 0x3b, 0x31,
	0x10, 0xc5, 0x69, 0x69, 0xbf, 0xfd, 0xee, 0x44, 0x3c, 0x44, 0x94, 0xd2, 0x83, 0x94, 0x3d, 0x55,
	0x84, 0x1c, 0xb6, 0x8a, 0x3d, 0xd7, 0x1f, 0x78, 0x58, 0x45, 0x96, 0xdc, 0x97, 0x34, 0x0d, 0x56,
	0x49, 0x37, 0x25, 0x3b, 0x0b, 0xfa, 0xdf, 0x4b, 0xd2, 0x36, 0xdb, 0x22, 0x88, 0x8b, 0xf4, 0xf6,
	0x32, 0x99, 0x4f, 0xde, 0x1b, 0x26, 0x30, 0x28, 0xe5, 0x42, 0x2d, 0x05, 0x43, 0xcd, 0xa4, 0xb1,
	0x2a, 0xc7, 0xcf, 0x95, 0x2a, 0xd9, 0xca, 0x1a, 0x34, 0xb4, 0xb7, 0x44, 0x2f, 0x06, 0xa7, 0x3b,
	0x4d, 0x56, 0x8e, 0x93, 0xf5, 0x7d, 0x4c, 0x20, 0x9a, 0x1a, 0xa3, 0xf3, 0x3b, 0x81, 0x22, 0x7e,
	0x87, 0x8e, 0x3b, 0xd0, 0x09, 0x10, 0x69, 0x8a, 0x12, 0x6d, 0x25, 0xd1, 0xd8, 0x7e, 0x6b, 0xd8,
	0x1a, 0x1d, 0x27, 0x67, 0x6c, 0xf3, 0x14, 0xe3, 0xe9, 0x6d, 0x7d, 0x9b, 0xed, 0xb6, 0xd2, 0x11,
	0x74, 0xe7, 0x02, 0x45, 0xd2, 0x6f, 0x0f, 0x5b, 0x23, 0x92, 0xd0, 0xc0, 0x04, 0x93, 0x6c, 0xdd,
	0x10, 0x4f, 0xe0, 0x88, 0xa7, 0xf9, 0xcc, 0x18, 0xfd, 0x20, 0x74, 0xa9, 0x1a, 0x90, 0x37, 0x40,
	0x36, 0x24, 0xb7, 0x55, 0x13, 0x90, 0x40, 0xe4, 0x88, 0x30, 0xab, 0xc7, 0x0f, 0x30, 0x6b, 0x30,
	0xd9, 0x1a, 0x8f, 0xa1, 0xc7, 0xd3, 0x1c, 0x7f, 0x4c, 0xfb, 0x0d, 0xba, 0x02, 0xb8, 0xb7, 0xd6,
	0x58, 0x5f, 0xa4, 0x14, 0x3a, 0xd2, 0xcc, 0x95, 0xcf, 0xd7, 0xcd, 0xbc, 0x76, 0x35, 0x54, 0x1f,
	0xe8, 0x9f, 0x8a, 0x32, 0xaf, 0x63, 0x0d, 0x5d, 0x4f, 0xfd, 0x61, 0xae, 0x8b, 0xfd, 0x88, 0x27,
	0x81, 0xa9, 0xe3, 0x6c, 0x33, 0x5e, 0xc3, 0x7f, 0x9e, 0xe6, 0xca, 0x1b, 0x36, 0xc0, 0x08, 0x44,
	0xcf, 0x95, 0xae, 0x3f, 0x9d, 0x3b, 0x1c, 0x62, 0x11, 0xc1, 0x64, 0x7f, 0x11, 0x85, 0xb3, 0xfb,
	0x35, 0x34, 0xbd, 0x84, 0x73, 0xb9, 0x10, 0xc8, 0x0a, 0x35, 0xab, 0xb4, 0x60, 0x4e, 0xab, 0xe2,
	0xf5, 0xad, 0x50, 0x5b, 0x64, 0xda, 0x7b, 0xe2, 0x2f, 0x4e, 0x3c, 0xb6, 0x67, 0xff, 0x7c, 0x65,
	0xfc, 0x15, 0x00, 0x00, 0xff, 0xff, 0x46, 0xce, 0x2e, 0x60, 0x94, 0x03, 0x00, 0x00,
}
