// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.tl.transport_service.proto

package mtproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// /////////////////////////////////////////////////////////////////////////////
// rpc_drop_answer#58e4a740 req_msg_id:long = RpcDropAnswer;
type TLRpcDropAnswer struct {
	ReqMsgId             int64    `protobuf:"varint,1,opt,name=req_msg_id,json=reqMsgId,proto3" json:"req_msg_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLRpcDropAnswer) Reset()         { *m = TLRpcDropAnswer{} }
func (m *TLRpcDropAnswer) String() string { return proto.CompactTextString(m) }
func (*TLRpcDropAnswer) ProtoMessage()    {}
func (*TLRpcDropAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_transport_service_99c1ca7bad01b6dd, []int{0}
}
func (m *TLRpcDropAnswer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLRpcDropAnswer.Unmarshal(m, b)
}
func (m *TLRpcDropAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLRpcDropAnswer.Marshal(b, m, deterministic)
}
func (dst *TLRpcDropAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLRpcDropAnswer.Merge(dst, src)
}
func (m *TLRpcDropAnswer) XXX_Size() int {
	return xxx_messageInfo_TLRpcDropAnswer.Size(m)
}
func (m *TLRpcDropAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_TLRpcDropAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_TLRpcDropAnswer proto.InternalMessageInfo

func (m *TLRpcDropAnswer) GetReqMsgId() int64 {
	if m != nil {
		return m.ReqMsgId
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
// get_future_salts#b921bd04 num:int = FutureSalts;
type TLGetFutureSalts struct {
	Num                  int32    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLGetFutureSalts) Reset()         { *m = TLGetFutureSalts{} }
func (m *TLGetFutureSalts) String() string { return proto.CompactTextString(m) }
func (*TLGetFutureSalts) ProtoMessage()    {}
func (*TLGetFutureSalts) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_transport_service_99c1ca7bad01b6dd, []int{1}
}
func (m *TLGetFutureSalts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLGetFutureSalts.Unmarshal(m, b)
}
func (m *TLGetFutureSalts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLGetFutureSalts.Marshal(b, m, deterministic)
}
func (dst *TLGetFutureSalts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLGetFutureSalts.Merge(dst, src)
}
func (m *TLGetFutureSalts) XXX_Size() int {
	return xxx_messageInfo_TLGetFutureSalts.Size(m)
}
func (m *TLGetFutureSalts) XXX_DiscardUnknown() {
	xxx_messageInfo_TLGetFutureSalts.DiscardUnknown(m)
}

var xxx_messageInfo_TLGetFutureSalts proto.InternalMessageInfo

func (m *TLGetFutureSalts) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
// ping#7abe77ec ping_id:long = Pong;
type TLPing struct {
	PingId               int64    `protobuf:"varint,1,opt,name=ping_id,json=pingId,proto3" json:"ping_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLPing) Reset()         { *m = TLPing{} }
func (m *TLPing) String() string { return proto.CompactTextString(m) }
func (*TLPing) ProtoMessage()    {}
func (*TLPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_transport_service_99c1ca7bad01b6dd, []int{2}
}
func (m *TLPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLPing.Unmarshal(m, b)
}
func (m *TLPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLPing.Marshal(b, m, deterministic)
}
func (dst *TLPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLPing.Merge(dst, src)
}
func (m *TLPing) XXX_Size() int {
	return xxx_messageInfo_TLPing.Size(m)
}
func (m *TLPing) XXX_DiscardUnknown() {
	xxx_messageInfo_TLPing.DiscardUnknown(m)
}

var xxx_messageInfo_TLPing proto.InternalMessageInfo

func (m *TLPing) GetPingId() int64 {
	if m != nil {
		return m.PingId
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
// ping_delay_disconnect#f3427b8c ping_id:long disconnect_delay:int = Pong;
type TLPingDelayDisconnect struct {
	PingId               int64    `protobuf:"varint,1,opt,name=ping_id,json=pingId,proto3" json:"ping_id,omitempty"`
	DisconnectDelay      int32    `protobuf:"varint,2,opt,name=disconnect_delay,json=disconnectDelay,proto3" json:"disconnect_delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLPingDelayDisconnect) Reset()         { *m = TLPingDelayDisconnect{} }
func (m *TLPingDelayDisconnect) String() string { return proto.CompactTextString(m) }
func (*TLPingDelayDisconnect) ProtoMessage()    {}
func (*TLPingDelayDisconnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_transport_service_99c1ca7bad01b6dd, []int{3}
}
func (m *TLPingDelayDisconnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLPingDelayDisconnect.Unmarshal(m, b)
}
func (m *TLPingDelayDisconnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLPingDelayDisconnect.Marshal(b, m, deterministic)
}
func (dst *TLPingDelayDisconnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLPingDelayDisconnect.Merge(dst, src)
}
func (m *TLPingDelayDisconnect) XXX_Size() int {
	return xxx_messageInfo_TLPingDelayDisconnect.Size(m)
}
func (m *TLPingDelayDisconnect) XXX_DiscardUnknown() {
	xxx_messageInfo_TLPingDelayDisconnect.DiscardUnknown(m)
}

var xxx_messageInfo_TLPingDelayDisconnect proto.InternalMessageInfo

func (m *TLPingDelayDisconnect) GetPingId() int64 {
	if m != nil {
		return m.PingId
	}
	return 0
}

func (m *TLPingDelayDisconnect) GetDisconnectDelay() int32 {
	if m != nil {
		return m.DisconnectDelay
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
// destroy_session#e7512126 session_id:long = DestroySessionRes;
type TLDestroySession struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLDestroySession) Reset()         { *m = TLDestroySession{} }
func (m *TLDestroySession) String() string { return proto.CompactTextString(m) }
func (*TLDestroySession) ProtoMessage()    {}
func (*TLDestroySession) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_transport_service_99c1ca7bad01b6dd, []int{4}
}
func (m *TLDestroySession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLDestroySession.Unmarshal(m, b)
}
func (m *TLDestroySession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLDestroySession.Marshal(b, m, deterministic)
}
func (dst *TLDestroySession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLDestroySession.Merge(dst, src)
}
func (m *TLDestroySession) XXX_Size() int {
	return xxx_messageInfo_TLDestroySession.Size(m)
}
func (m *TLDestroySession) XXX_DiscardUnknown() {
	xxx_messageInfo_TLDestroySession.DiscardUnknown(m)
}

var xxx_messageInfo_TLDestroySession proto.InternalMessageInfo

func (m *TLDestroySession) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

// /////////////////////////////////////////////////////////////////////////////
// contest.saveDeveloperInfo#9a5f6e95 vk_id:int name:string phone_number:string age:int city:string = Bool;
type TLContestSaveDeveloperInfo struct {
	VkId                 int32    `protobuf:"varint,1,opt,name=vk_id,json=vkId,proto3" json:"vk_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Age                  int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TLContestSaveDeveloperInfo) Reset()         { *m = TLContestSaveDeveloperInfo{} }
func (m *TLContestSaveDeveloperInfo) String() string { return proto.CompactTextString(m) }
func (*TLContestSaveDeveloperInfo) ProtoMessage()    {}
func (*TLContestSaveDeveloperInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_transport_service_99c1ca7bad01b6dd, []int{5}
}
func (m *TLContestSaveDeveloperInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TLContestSaveDeveloperInfo.Unmarshal(m, b)
}
func (m *TLContestSaveDeveloperInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TLContestSaveDeveloperInfo.Marshal(b, m, deterministic)
}
func (dst *TLContestSaveDeveloperInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLContestSaveDeveloperInfo.Merge(dst, src)
}
func (m *TLContestSaveDeveloperInfo) XXX_Size() int {
	return xxx_messageInfo_TLContestSaveDeveloperInfo.Size(m)
}
func (m *TLContestSaveDeveloperInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TLContestSaveDeveloperInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TLContestSaveDeveloperInfo proto.InternalMessageInfo

func (m *TLContestSaveDeveloperInfo) GetVkId() int32 {
	if m != nil {
		return m.VkId
	}
	return 0
}

func (m *TLContestSaveDeveloperInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TLContestSaveDeveloperInfo) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *TLContestSaveDeveloperInfo) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *TLContestSaveDeveloperInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func init() {
	proto.RegisterType((*TLRpcDropAnswer)(nil), "mtproto.TL_rpc_drop_answer")
	proto.RegisterType((*TLGetFutureSalts)(nil), "mtproto.TL_get_future_salts")
	proto.RegisterType((*TLPing)(nil), "mtproto.TL_ping")
	proto.RegisterType((*TLPingDelayDisconnect)(nil), "mtproto.TL_ping_delay_disconnect")
	proto.RegisterType((*TLDestroySession)(nil), "mtproto.TL_destroy_session")
	proto.RegisterType((*TLContestSaveDeveloperInfo)(nil), "mtproto.TL_contest_saveDeveloperInfo")
}

func init() {
	proto.RegisterFile("schema.tl.transport_service.proto", fileDescriptor_schema_tl_transport_service_99c1ca7bad01b6dd)
}

var fileDescriptor_schema_tl_transport_service_99c1ca7bad01b6dd = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0xd5, 0x6d, 0xb3, 0x61, 0x07, 0x24, 0x56, 0xde, 0x03, 0x39, 0x14, 0x44, 0x73, 0x01,
	0x84, 0x94, 0x03, 0x7d, 0x83, 0xaa, 0x07, 0x22, 0xa5, 0x08, 0x45, 0x39, 0x33, 0x72, 0xed, 0x69,
	0x1a, 0x35, 0xb1, 0x53, 0xdb, 0x09, 0xea, 0x5b, 0xf0, 0xc8, 0xc8, 0x6e, 0x50, 0x4e, 0x9c, 0xf2,
	0xe5, 0xf3, 0xcc, 0x6f, 0x7b, 0x0c, 0x1b, 0x2b, 0xce, 0xd4, 0xf1, 0xcc, 0xb5, 0x99, 0x33, 0x5c,
	0xd9, 0x5e, 0x1b, 0x87, 0x96, 0xcc, 0xd8, 0x08, 0xca, 0x7a, 0xa3, 0x9d, 0x66, 0x71, 0xe7, 0x02,
	0xa4, 0xdf, 0x80, 0x55, 0x05, 0x9a, 0x5e, 0xa0, 0x34, 0xba, 0x47, 0xae, 0xec, 0x6f, 0x32, 0x6c,
	0x0d, 0x60, 0xe8, 0x8a, 0x9d, 0xad, 0xb1, 0x91, 0xc9, 0xe2, 0xe3, 0xe2, 0xf3, 0xb2, 0x7c, 0x65,
	0xe8, 0x7a, 0xb0, 0x75, 0x2e, 0xd3, 0x4f, 0xf0, 0x52, 0x15, 0x58, 0x93, 0xc3, 0xd3, 0xe0, 0x06,
	0x43, 0x68, 0x79, 0xeb, 0x2c, 0x7b, 0x86, 0xa5, 0x1a, 0xba, 0x50, 0x1d, 0x95, 0x1e, 0xd3, 0x14,
	0xe2, 0xaa, 0xc0, 0xbe, 0x51, 0x35, 0x7b, 0x07, 0xb1, 0xff, 0xce, 0x71, 0x8f, 0xfe, 0x37, 0x97,
	0xe9, 0x2f, 0x48, 0xa6, 0x1a, 0x94, 0xd4, 0xf2, 0x1b, 0xca, 0xc6, 0x0a, 0xad, 0x14, 0x09, 0xf7,
	0xdf, 0x26, 0xf6, 0x05, 0x9e, 0xe7, 0xb2, 0x7b, 0x5f, 0xf2, 0x10, 0xf6, 0x7d, 0x3b, 0xfb, 0xbd,
	0xd7, 0xe9, 0x36, 0x5c, 0x50, 0x92, 0x75, 0x46, 0xdf, 0xd0, 0x92, 0xb5, 0x8d, 0x56, 0xec, 0x3d,
	0xc0, 0x84, 0x73, 0xf8, 0xd3, 0x64, 0x72, 0x99, 0xfe, 0x59, 0xc0, 0xba, 0x2a, 0x50, 0x68, 0xe5,
	0xc8, 0x3a, 0xb4, 0x7c, 0xa4, 0x3d, 0x8d, 0xd4, 0xea, 0x9e, 0x4c, 0xae, 0x4e, 0x9a, 0xbd, 0x40,
	0x34, 0x5e, 0xfe, 0xb5, 0x46, 0xe5, 0x6a, 0xbc, 0xe4, 0x92, 0x31, 0x58, 0x29, 0xde, 0x51, 0x38,
	0xc9, 0x53, 0x19, 0x98, 0x6d, 0xe0, 0x4d, 0x7f, 0xd6, 0x8a, 0x50, 0x0d, 0xdd, 0x91, 0x4c, 0xb2,
	0x0c, 0x6b, 0xaf, 0x83, 0xfb, 0x11, 0x94, 0x9f, 0x1b, 0xaf, 0x29, 0x59, 0xdd, 0xe7, 0xc6, 0x6b,
	0xf2, 0x41, 0xa2, 0x71, 0xb7, 0x24, 0xba, 0x07, 0x79, 0xde, 0x7d, 0x85, 0x0f, 0xe2, 0xcc, 0x5d,
	0xa6, 0xe8, 0x38, 0xb4, 0x3c, 0xf3, 0x4c, 0xaa, 0x6e, 0x14, 0x65, 0xd3, 0x53, 0xee, 0xe2, 0x43,
	0xf5, 0xd3, 0xc3, 0xf7, 0x87, 0xe3, 0x63, 0x30, 0xdb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6f,
	0x7e, 0x69, 0x19, 0x0a, 0x02, 0x00, 0x00,
}
