// Code generated by protoc-gen-go. DO NOT EDIT.
// source: privacy_rules_data.proto

/*
Package account is a generated protocol buffer package.

It is generated from these files:
	privacy_rules_data.proto

It has these top-level messages:
	PrivacyRuleData
	PrivacyRulesData
*/
package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// privacyKeyStatusTimestamp#bc2eab30 = PrivacyKey;
// privacyKeyChatInvite#500e6dfa = PrivacyKey;
// privacyKeyPhoneCall#3d662b7b = PrivacyKey;
type PrivacyKeyType int32

const (
	PrivacyKeyType_KEY_TYPE_INVALID PrivacyKeyType = 0
	PrivacyKeyType_STATUS_TIMESTAMP PrivacyKeyType = 1
	PrivacyKeyType_CHAT_INVITE      PrivacyKeyType = 2
	PrivacyKeyType_PHONE_CALL       PrivacyKeyType = 3
)

var PrivacyKeyType_name = map[int32]string{
	0: "KEY_TYPE_INVALID",
	1: "STATUS_TIMESTAMP",
	2: "CHAT_INVITE",
	3: "PHONE_CALL",
}
var PrivacyKeyType_value = map[string]int32{
	"KEY_TYPE_INVALID": 0,
	"STATUS_TIMESTAMP": 1,
	"CHAT_INVITE":      2,
	"PHONE_CALL":       3,
}

func (x PrivacyKeyType) String() string {
	return proto.EnumName(PrivacyKeyType_name, int32(x))
}
func (PrivacyKeyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// privacyValueAllowContacts#fffe1bac = PrivacyRule;
// privacyValueAllowAll#65427b82 = PrivacyRule;
// privacyValueAllowUsers#4d5bbe0c users:Vector<int> = PrivacyRule;
// privacyValueDisallowContacts#f888fa1a = PrivacyRule;
// privacyValueDisallowAll#8b73e763 = PrivacyRule;
// privacyValueDisallowUsers#c7f49b7 users:Vector<int> = PrivacyRule;
type PrivacyRuleType int32

const (
	PrivacyRuleType_RULE_TYPE_INVALID PrivacyRuleType = 0
	PrivacyRuleType_ALLOW_CONTACTS    PrivacyRuleType = 1
	PrivacyRuleType_ALLOW_ALL         PrivacyRuleType = 2
	PrivacyRuleType_ALLOW_USERS       PrivacyRuleType = 3
	PrivacyRuleType_DISALLOW_CONTACTS PrivacyRuleType = 4
	PrivacyRuleType_DISALLOW_ALL      PrivacyRuleType = 5
	PrivacyRuleType_DISALLOW_USERS    PrivacyRuleType = 6
)

var PrivacyRuleType_name = map[int32]string{
	0: "RULE_TYPE_INVALID",
	1: "ALLOW_CONTACTS",
	2: "ALLOW_ALL",
	3: "ALLOW_USERS",
	4: "DISALLOW_CONTACTS",
	5: "DISALLOW_ALL",
	6: "DISALLOW_USERS",
}
var PrivacyRuleType_value = map[string]int32{
	"RULE_TYPE_INVALID": 0,
	"ALLOW_CONTACTS":    1,
	"ALLOW_ALL":         2,
	"ALLOW_USERS":       3,
	"DISALLOW_CONTACTS": 4,
	"DISALLOW_ALL":      5,
	"DISALLOW_USERS":    6,
}

func (x PrivacyRuleType) String() string {
	return proto.EnumName(PrivacyRuleType_name, int32(x))
}
func (PrivacyRuleType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PrivacyRuleData struct {
	Type       PrivacyRuleType `protobuf:"varint,1,opt,name=type,enum=account.PrivacyRuleType" json:"type,omitempty"`
	UserIdList []int32         `protobuf:"varint,2,rep,packed,name=user_id_list,json=userIdList" json:"user_id_list,omitempty"`
}

func (m *PrivacyRuleData) Reset()                    { *m = PrivacyRuleData{} }
func (m *PrivacyRuleData) String() string            { return proto.CompactTextString(m) }
func (*PrivacyRuleData) ProtoMessage()               {}
func (*PrivacyRuleData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PrivacyRuleData) GetType() PrivacyRuleType {
	if m != nil {
		return m.Type
	}
	return PrivacyRuleType_RULE_TYPE_INVALID
}

func (m *PrivacyRuleData) GetUserIdList() []int32 {
	if m != nil {
		return m.UserIdList
	}
	return nil
}

type PrivacyRulesData struct {
	Rules []*PrivacyRuleData `protobuf:"bytes,1,rep,name=rules" json:"rules,omitempty"`
}

func (m *PrivacyRulesData) Reset()                    { *m = PrivacyRulesData{} }
func (m *PrivacyRulesData) String() string            { return proto.CompactTextString(m) }
func (*PrivacyRulesData) ProtoMessage()               {}
func (*PrivacyRulesData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PrivacyRulesData) GetRules() []*PrivacyRuleData {
	if m != nil {
		return m.Rules
	}
	return nil
}

func init() {
	proto.RegisterType((*PrivacyRuleData)(nil), "account.PrivacyRuleData")
	proto.RegisterType((*PrivacyRulesData)(nil), "account.PrivacyRulesData")
	proto.RegisterEnum("account.PrivacyKeyType", PrivacyKeyType_name, PrivacyKeyType_value)
	proto.RegisterEnum("account.PrivacyRuleType", PrivacyRuleType_name, PrivacyRuleType_value)
}

func init() { proto.RegisterFile("privacy_rules_data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xd1, 0x6a, 0xa3, 0x40,
	0x14, 0x86, 0x57, 0x4d, 0xb2, 0xec, 0x49, 0xd6, 0xcc, 0xce, 0xb6, 0xc5, 0x4b, 0xc9, 0x55, 0x08,
	0x45, 0x68, 0xfb, 0x04, 0xc6, 0x08, 0x91, 0x98, 0x44, 0x74, 0xd2, 0x92, 0x42, 0x19, 0x26, 0x66,
	0x2e, 0x04, 0x13, 0x45, 0xc7, 0x82, 0x7d, 0x93, 0xbe, 0x6d, 0x19, 0x0d, 0x21, 0x0d, 0xbd, 0x12,
	0xff, 0xf9, 0xfe, 0xf3, 0x0d, 0x67, 0xc0, 0xc8, 0x8b, 0xe4, 0x9d, 0xc5, 0x35, 0x2d, 0xaa, 0x94,
	0x97, 0x74, 0xcf, 0x04, 0xb3, 0xf2, 0x22, 0x13, 0x19, 0xfe, 0xcd, 0xe2, 0x38, 0xab, 0x8e, 0x62,
	0xc4, 0x60, 0x18, 0xb4, 0x50, 0x58, 0xa5, 0x7c, 0xc6, 0x04, 0xc3, 0xf7, 0xd0, 0x11, 0x75, 0xce,
	0x0d, 0xc5, 0x54, 0xc6, 0xfa, 0xa3, 0x61, 0x9d, 0x50, 0xeb, 0x82, 0x23, 0x75, 0xce, 0xc3, 0x86,
	0xc2, 0x26, 0x0c, 0xaa, 0x92, 0x17, 0x34, 0xd9, 0xd3, 0x34, 0x29, 0x85, 0xa1, 0x9a, 0xda, 0xb8,
	0x1b, 0x82, 0xcc, 0xbc, 0xbd, 0x9f, 0x94, 0x62, 0x34, 0x05, 0x74, 0x51, 0x2d, 0x1b, 0x87, 0x05,
	0xdd, 0xe6, 0x4e, 0x86, 0x62, 0x6a, 0xe3, 0xfe, 0xcf, 0x12, 0x09, 0x86, 0x2d, 0x36, 0x79, 0x03,
	0xfd, 0x74, 0xb2, 0xe0, 0xb5, 0xb4, 0xe3, 0x1b, 0x40, 0x0b, 0x77, 0x4b, 0xc9, 0x36, 0x70, 0xa9,
	0xb7, 0x7a, 0xb6, 0x7d, 0x6f, 0x86, 0x7e, 0xc9, 0x34, 0x22, 0x36, 0xd9, 0x44, 0x94, 0x78, 0x4b,
	0x37, 0x22, 0xf6, 0x32, 0x40, 0x0a, 0x1e, 0x42, 0xdf, 0x99, 0xdb, 0x44, 0x72, 0x1e, 0x71, 0x91,
	0x8a, 0x75, 0x80, 0x60, 0xbe, 0x5e, 0xb9, 0xd4, 0xb1, 0x7d, 0x1f, 0x69, 0x93, 0x4f, 0xe5, 0xdb,
	0x1a, 0x1a, 0xc1, 0x2d, 0xfc, 0x0b, 0x37, 0xbe, 0x7b, 0x6d, 0xc0, 0xa0, 0xdb, 0xbe, 0xbf, 0x7e,
	0xa1, 0xce, 0x7a, 0x45, 0x6c, 0x87, 0x44, 0x48, 0xc1, 0x7f, 0xe1, 0x4f, 0x9b, 0xc9, 0x69, 0xaa,
	0xd4, 0xb5, 0xbf, 0x9b, 0xc8, 0x0d, 0x23, 0xa4, 0xc9, 0x51, 0x33, 0x2f, 0xba, 0xaa, 0x75, 0x30,
	0x82, 0xc1, 0x39, 0x96, 0xcd, 0xae, 0x1c, 0x7e, 0x4e, 0xda, 0x72, 0x6f, 0xfa, 0x00, 0xff, 0xe3,
	0xec, 0x60, 0x1d, 0xf9, 0xae, 0x4a, 0x59, 0x72, 0xb0, 0x3e, 0x9a, 0x17, 0x9c, 0xde, 0xbd, 0x06,
	0xf2, 0x7b, 0xbd, 0xd9, 0xb9, 0x1a, 0x28, 0xbb, 0x5e, 0x83, 0x3c, 0x7d, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x1f, 0x25, 0xc8, 0xbd, 0x00, 0x02, 0x00, 0x00,
}
